import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'dart:math';
void main()=>runApp(const PlayAndWinApp());
class PlayAndWinApp extends StatelessWidget{const PlayAndWinApp({super.key}); @override Widget build(BuildContext c)=>const MaterialApp(debugShowCheckedModeBanner:false, home:LobbyScreen());}

class LobbyScreen extends StatefulWidget{const LobbyScreen({super.key}); @override State<LobbyScreen> createState()=>_LobbyState();}
class _LobbyState extends State<LobbyScreen>{
  List<Map<String,String>> requests=[{"n":"أحمد","v":"V5","i":"10"},{"n":"نور","v":"V8","i":"11"}];
  List<String> globalChat=["همام: يلا نلعب؟","سحاب: أنا جاهز"];
  TextEditingController chatCtrl=TextEditingController();
  List<Map<String,String>> getFullPlayers(List<Map<String,String>> real){
    List<Map<String,String>> all=List.from(real);
    List<Map<String,String>> bots=[{"n":"روبوت 1","v":"BOT","i":"20"},{"n":"روبوت 2","v":"BOT","i":"21"},{"n":"روبوت 3","v":"BOT","i":"22"}];
    int need=4-all.length; for(int i=0;i<need;i++) all.add(bots[i]); return all;
  }
  void showPrivate(String name){showDialog(context:context, builder:(_)=>AlertDialog(backgroundColor:const Color(0xFF1C2A45), title:Text("شات خاص مع $name", style:const TextStyle(color:Colors.white, fontSize:12))));}
  void showReq(){showModalBottomSheet(context:context, backgroundColor:const Color(0xFF0E172A), shape:const RoundedRectangleBorder(borderRadius:BorderRadius.vertical(top:Radius.circular(24))), builder:(_)=>Padding(padding:const EdgeInsets.all(16), child:Column(mainAxisSize:MainAxisSize.min, children:[const Text("طلبات الصداقة", style:TextStyle(color:Colors.white, fontWeight:FontWeight.bold)), const SizedBox(height:12),...requests.map((r)=>Container(margin:const EdgeInsets.only(bottom:10), padding:const EdgeInsets.all(12), decoration:BoxDecoration(color:const Color(0xFF1C2A45), borderRadius:BorderRadius.circular(12)), child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween, children:[Text(r["n"]!, style:const TextStyle(color:Colors.white)), Row(children:[Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:6), decoration:BoxDecoration(color:Colors.green, borderRadius:BorderRadius.circular(20)), child:const Text("قبول", style:TextStyle(color:Colors.white, fontSize:11))), const SizedBox(width:6), Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:6), decoration:BoxDecoration(color:Colors.white24, borderRadius:BorderRadius.circular(20)), child:const Text("رفض", style:TextStyle(color:Colors.white, fontSize:11)))])])))])));}

  @override Widget build(BuildContext context){
    final friends=[{"n":"همام","v":"V6","i":"1"},{"n":"سحاب","v":"V7","i":"2"}]; final display=getFullPlayers(friends);
    return Scaffold(backgroundColor:const Color(0xFF0A1020), body:SafeArea(child:Column(children:[
      Container(padding:const EdgeInsets.all(12), color:const Color(0xFF1A2332), child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween, children:[Row(children:[const CircleAvatar(radius:16, backgroundImage:NetworkImage('https://i.pravatar.cc/100?img=12')), const SizedBox(width:6), Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:5), decoration:BoxDecoration(color:Colors.black45, borderRadius:BorderRadius.circular(20)), child:const Text("🪙 1500 +", style:TextStyle(color:Colors.white, fontSize:11))), const SizedBox(width:6), GestureDetector(onTap:showReq, child:Container(padding:const EdgeInsets.all(6), decoration:BoxDecoration(color:Colors.black26, borderRadius:BorderRadius.circular(20)), child:const Text("👥 2", style:TextStyle(color:Colors.white, fontSize:11))))]), const Text("🔍 👑 TOP", style:TextStyle(color:Colors.white, fontSize:11)) ])),
      Expanded(child:SingleChildScrollView(child:Column(children:[
        Padding(padding:const EdgeInsets.all(14), child:GridView.count(shrinkWrap:true, physics:const NeverScrollableScrollPhysics(), crossAxisCount:2, childAspectRatio:0.85, mainAxisSpacing:14, crossAxisSpacing:12, children:[
          _prettyCard(context,"بلياردو",[const Color(0xFFFF9800), const Color(0xFF5D4037)],"🎯", BilliardScreen(chat:globalChat)),
          _prettyCard(context,"دومينو 50",[const Color(0xFF66BB6A), const Color(0xFF1B5E20)],"🀄", DominoScreen(chat:globalChat)),
          _prettyCard(context,"لودو",[const Color(0xFF42A5F5), const Color(0xFF0D47A1)],"🎲", LudoScreen(chat:globalChat)),
          _prettyCard(context,"سلم وثعبان",[const Color(0xFFBA68C8), const Color(0xFF4A148C)],"🐍", SnakeScreen(chat:globalChat)),
        ])),
        Container(decoration:const BoxDecoration(color:Color(0xFF0E172A), borderRadius:BorderRadius.vertical(top:Radius.circular(20))), padding:const EdgeInsets.all(12), child:Column(children:[
          const Text("غرفة الانتظار - روبوتات تكمل لو مفيش حقيقيين", style:TextStyle(color:Colors.white70, fontSize:10)),
          const SizedBox(height:8),
         ...display.map((f)=>GestureDetector(onTap:()=>showPrivate(f["n"]!), child:Container(margin:const EdgeInsets.only(bottom:8), padding:const EdgeInsets.all(10), decoration:BoxDecoration(color:const Color(0xFF1C2A45), borderRadius:BorderRadius.circular(12)), child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween, children:[Row(children:[CircleAvatar(radius:18, backgroundImage:NetworkImage('https://i.pravatar.cc/100?img=${f["i"]}')), const SizedBox(width:8), Text(f["n"]!, style:const TextStyle(color:Colors.white, fontSize:12))]), Text(f["v"]!, style:const TextStyle(color:Colors.amber, fontSize:9))])))),
        ]))
      ]))),
      Container(padding:const EdgeInsets.all(8), color:const Color(0xFF1A2332), child:Row(children:[Expanded(child:TextField(controller:chatCtrl, style:const TextStyle(color:Colors.white, fontSize:11), decoration:InputDecoration(hintText:"دردشة عامة في كل الألعاب - قل شيئا...", hintStyle:const TextStyle(color:Colors.white54, fontSize:10), filled:true, fillColor:Colors.black45, border:OutlineInputBorder(borderRadius:BorderRadius.circular(20), borderSide:BorderSide.none)))), const SizedBox(width:6), GestureDetector(onTap:(){ if(chatCtrl.text.isNotEmpty){ setState(()=> globalChat.add("أنت: ${chatCtrl.text}")); chatCtrl.clear(); } }, child:Container(padding:const EdgeInsets.all(10), decoration:const BoxDecoration(color:Colors.amber, shape:BoxShape.circle), child:const Icon(Icons.send, size:14))) ]))
    ])));
  }
  Widget _prettyCard(BuildContext c,String t,List<Color> col,String e,Widget p)=>GestureDetector(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>p)), child:Container(decoration:BoxDecoration(gradient:LinearGradient(colors:col), borderRadius:BorderRadius.circular(20), boxShadow:[BoxShadow(color:col[0].withOpacity(0.4), blurRadius:10, offset:const Offset(0,5))]), child:Column(mainAxisAlignment:MainAxisAlignment.center, children:[Text(e, style:const TextStyle(fontSize:38)), const SizedBox(height:6), Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:5), decoration:BoxDecoration(color:Colors.black54, borderRadius:BorderRadius.circular(14)), child:Text(t, style:const TextStyle(color:Colors.white, fontSize:10, fontWeight:FontWeight.bold)))])));
}

// ===== بلياردو =====
class BilliardScreen extends StatefulWidget{final List<String> chat; const BilliardScreen({super.key, required this.chat}); @override State<BilliardScreen> createState()=>_BState();}
class _BState extends State<BilliardScreen> with SingleTickerProviderStateMixin{
  Offset? ds,dc; Offset cue=const Offset(130,330); Offset vel=Offset.zero; List<Ball> balls=[]; late Ticker tk;
  @override void initState(){super.initState(); _reset(); tk=createTicker((d){ if(vel==Offset.zero) return; setState((){ cue+=vel; vel*=0.998; if(vel.distance<0.2) vel=Offset.zero; if(cue.dx<16||cue.dx>244) vel=Offset(-vel.dx, vel.dy); if(cue.dy<16||cue.dy>384) vel=Offset(vel.dx, -vel.dy); }); }); tk.start();}
  void _reset(){ balls=[]; double sx=130, sy=70; List<Color> cs=[Colors.yellow, Colors.blue, Colors.red]; int k=0; for(int r=0;r<4;r++){ for(int c=0;c<=r;c++){ balls.add(Ball(Offset(sx+(c-r/2)*13, sy+r*13), cs[k%3])); k++; }}}
  @override void dispose(){tk.dispose(); super.dispose();}
  @override Widget build(BuildContext context){ return Scaffold(backgroundColor:const Color(0xFF0A1020), appBar:AppBar(backgroundColor:const Color(0xFF1A2332), title:const Text("بلياردو - 260x400 خفيف", style:TextStyle(fontSize:11))), body:Column(children:[Expanded(child:Center(child:SizedBox(width:260, height:400, child:GestureDetector(onPanStart:(d)=>ds=d.localPosition, onPanUpdate:(d)=>dc=d.localPosition, onPanEnd:(_){ if(ds!=null&&dc!=null) vel=(ds!-dc!)*0.35; ds=null; dc=null; }, child:CustomPaint(painter:PoolPainter(cue,balls,ds,dc)))))), Container(padding:const EdgeInsets.all(8), color:const Color(0xFF1A2332), child:Row(mainAxisAlignment:MainAxisAlignment.spaceAround, children:List.generate(4, (i)=>CircleAvatar(radius:14, backgroundImage:NetworkImage('https://i.pravatar.cc/100?img=${i+1}'))))), _chatBar(widget.chat)])); }
}
class Ball{Offset pos; Color color; Ball(this.pos,this.color);}
class PoolPainter extends CustomPainter{final Offset cue; final List<Ball> balls; final Offset? s,c; PoolPainter(this.cue,this.balls,this.s,this.c); @override void paint(Canvas ca, Size sz){ ca.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(0,0,sz.width,sz.height), const Radius.circular(16)), Paint()..color=const Color(0xFF5D4037)); ca.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(6,6,sz.width-12,sz.height-12), const Radius.circular(12)), Paint()..color=const Color(0xFF2E7D32)); var ps=[Offset(8,8), Offset(sz.width/2,5), Offset(sz.width-8,8), Offset(8,sz.height-8), Offset(sz.width/2,sz.height-5), Offset(sz.width-8,sz.height-8)]; for(var p in ps){ ca.drawCircle(p, 15, Paint()..color=Colors.black); } for(var b in balls){ ca.drawCircle(b.pos, 6.5, Paint()..color=b.color); } ca.drawCircle(cue, 7.5, Paint()..color=Colors.white); if(s!=null&&c!=null) ca.drawLine(cue, cue+(s!-c!)*0.8, Paint()..color=Colors.yellow..strokeWidth=2); } @override bool shouldRepaint(covariant _)=>true; }

// ===== دومينو =====
class DominoScreen extends StatefulWidget{final List<String> chat; const DominoScreen({super.key, required this.chat}); @override State<DominoScreen> createState()=>_DState();}
class _DState extends State<DominoScreen>{ List<List<int>> board=[[3,3]]; @override Widget build(BuildContext context){ return Scaffold(backgroundColor:const Color(0xFF2E7D32), appBar:AppBar(backgroundColor:const Color(0xFF1A2332), title:const Text("دومينو - ورق صغير 32", style:TextStyle(fontSize:11))), body:Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween, children:[_p("روبوت 1","20"), const Text("دومينو 50", style:TextStyle(color:Colors.white, fontSize:11)), _p("روبوت 2","21")]), Center(child:Container(width:320, height:76, margin:const EdgeInsets.all(8), decoration:BoxDecoration(color:Colors.black26, borderRadius:BorderRadius.circular(10)), child:Row(children:board.map((t)=>_tile(t[0],t[1])).toList()))), const Spacer(), _chatBar(widget.chat)])); } Widget _p(String n,String i)=>Column(children:[CircleAvatar(radius:15, backgroundImage:NetworkImage('https://i.pravatar.cc/100?img=$i')), Text(n, style:const TextStyle(color:Colors.white, fontSize:8))]); Widget _tile(int a,int b)=>Container(width:32, height:48, margin:const EdgeInsets.all(2), decoration:BoxDecoration(color:Colors.white, borderRadius:BorderRadius.circular(4)), child:Column(children:[Expanded(child:CustomPaint(painter:DotPainter(a))), Container(height:1, color:Colors.black26), Expanded(child:CustomPaint(painter:DotPainter(b))) ])); }
class DotPainter extends CustomPainter{final int n; DotPainter(this.n); @override void paint(Canvas c, Size s){ if(n==0) return; var p=Paint()..color=Colors.black; var w=s.width, h=s.height; List<Offset> o=[]; if(n==1) o=[Offset(w/2,h/2)]; if(n==2) o=[Offset(w*0.25,h*0.25), Offset(w*0.75,h*0.75)]; if(n==3) o=[Offset(w*0.25,h*0.25), Offset(w/2,h/2), Offset(w*0.75,h*0.75)]; if(n>=4) o=[Offset(w*0.25,h*0.25), Offset(w*0.75,h*0.25), Offset(w*0.25,h*0.75), Offset(w*0.75,h*0.75)]; for(var e in o) c.drawCircle(e, 1.6, p); } @override bool shouldRepaint(covariant _)=>false; }

// ===== لودو =====
class LudoScreen extends StatefulWidget{final List<String> chat; const LudoScreen({super.key, required this.chat}); @override State<LudoScreen> createState()=>_LState();}
class _LState extends State<LudoScreen>{ @override Widget build(BuildContext context){ return Scaffold(backgroundColor:const Color(0xFF0F2A66), appBar:AppBar(backgroundColor:const Color(0xFF1A2332), title:const Text("لودو - 280 مع طيارات", style:TextStyle(fontSize:11))), body:Column(children:[Center(child:SizedBox(width:280, height:280, child:CustomPaint(painter:LudoPainter(), size:const Size(280,280)))), const Spacer(), Container(padding:const EdgeInsets.all(6), color:const Color(0xFF1A2332), child:Row(mainAxisAlignment:MainAxisAlignment.spaceAround, children:[_av("همام","1"), _av("سحاب","2"), _av("روبوت","20"), _av("الاكابر","3")])), _chatBar(widget.chat)])); } Widget _av(String n,String i)=>Column(children:[CircleAvatar(radius:14, backgroundImage:NetworkImage('https://i.pravatar.cc/100?img=$i')), Text(n, style:const TextStyle(color:Colors.white, fontSize:8))]); }
class LudoPainter extends CustomPainter{ @override void paint(Canvas c, Size s){ double cl=s.width/15; c.drawRect(Rect.fromLTWH(0,0,s.width,s.height), Paint()..color=Colors.white); c.drawRect(Rect.fromLTWH(0,0,6*cl,6*cl), Paint()..color=Colors.red); c.drawRect(Rect.fromLTWH(9*cl,0,6*cl,6*cl), Paint()..color=Colors.green); c.drawRect(Rect.fromLTWH(0,9*cl,6*cl,6*cl), Paint()..color=Colors.blue); c.drawRect(Rect.fromLTWH(9*cl,9*cl,6*cl,6*cl), Paint()..color=Colors.yellow); List<Offset> reds=[Offset(1.5*cl,1.5*cl), Offset(4.5*cl,1.5*cl), Offset(1.5*cl,4.5*cl), Offset(4.5*cl,4.5*cl)]; for(var p in reds){ c.drawCircle(p, 6, Paint()..color=Colors.white); } } @override bool shouldRepaint(covariant _)=>false; }

// ===== سلم وثعبان =====
class SnakeScreen extends StatefulWidget{final List<String> chat; const SnakeScreen({super.key, required this.chat}); @override State<SnakeScreen> createState()=>_SState();}
class _SState extends State<SnakeScreen>{ int p1=1,p2=12; final Map<int,int> snakes={99:54, 70:38, 62:19, 56:8}; final Map<int,int> ladders={3:22,5:8,11:26,20:29,27:56,21:42,36:51}; @override Widget build(BuildContext context){ return Scaffold(backgroundColor:const Color(0xFFFEF3C7), appBar:AppBar(backgroundColor:const Color(0xFF1A2332), title:const Text("سلم وثعبان - ثعبان منحني", style:TextStyle(fontSize:11))), body:Column(children:[Center(child:SizedBox(width:320, height:380, child:CustomPaint(painter:SnakePainter(p1,p2,snakes,ladders), size:const Size(320,380)))), const Spacer(), _chatBar(widget.chat)])); }}
class SnakePainter extends CustomPainter{final int pl1,pl2; final Map<int,int> snakes,ladders; SnakePainter(this.pl1,this.pl2,this.snakes,this.ladders); @override void paint(Canvas canvas, Size size){ double w=size.width/10, h=size.height/10; int num=100; for(int r=0;r<10;r++){ for(int c=0;c<10;c++){ int col=r%2==0? c: 9-c; var rect=Rect.fromLTWH(col*w, r*h, w, h); Color cr; if(num%2==0) cr=const Color(0xFFFFEB3B); else cr=Colors.white; canvas.drawRect(rect, Paint()..color=cr); canvas.drawRect(rect, Paint()..color=Colors.black26..style=PaintingStyle.stroke..strokeWidth=0.3); var tp=TextPainter(text:TextSpan(text:"$num", style:const TextStyle(fontSize:7, color:Colors.black)), textDirection:TextDirection.ltr)..layout(); tp.paint(canvas, Offset(rect.left+2, rect.top+1)); num--; } }
  var body=Paint()..color=Colors.black..strokeWidth=6..style=PaintingStyle.stroke..strokeCap=StrokeCap.round; snakes.forEach((s,e){ var sp=Offset(((100-s)%10)*w+w/2, ((100-s)~/10)*h+h/2); var ep=Offset(((100-e)%10)*w+w/2, ((100-e)~/10)*h+h/2); var mid=Offset((sp.dx+ep.dx)/2+20, (sp.dy+ep.dy)/2); var path=Path()..moveTo(sp.dx, sp.dy)..quadraticBezierTo(mid.dx-15, mid.dy-10, mid.dx, mid.dy)..quadraticBezierTo(mid.dx+15, mid.dy+10, ep.dx, ep.dy); canvas.drawPath(path, body); canvas.drawCircle(sp, 7, Paint()..color=const Color(0xFF4A0000)); });
  var lP=Paint()..color=const Color(0xFFFFC107)..strokeWidth=3..style=PaintingStyle.stroke; ladders.forEach((s,e){ var sp=Offset(((s-1)%10)*w+w/2, (9-(s-1)~/10)*h+h/2); var ep=Offset(((e-1)%10)*w+w/2, (9-(e-1)~/10)*h+h/2); canvas.drawLine(sp, ep, lP); canvas.drawLine(sp.translate(7,0), ep.translate(7,0), lP); });
} @override bool shouldRepaint(covariant _)=>true; }

Widget _chatBar(List<String> chat){ return Container(padding:const EdgeInsets.all(6), color:const Color(0xFF1A2332), child:Row(children:[const Text("💬 عام 59 🎁", style:TextStyle(color:Colors.white, fontSize:10)), const SizedBox(width:6), Expanded(child:Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6), decoration:BoxDecoration(color:Colors.black45, borderRadius:BorderRadius.circular(16)), child:const Text("دردشة عامة تعمل بكل الألعاب - قل شيئا - عام وخاص", style:TextStyle(color:Colors.white54, fontSize:8))))])); }
