name: Build and Deploy Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          cache: true

      - name: Clean and Recreate Modern Android Project
        run: |
          # حذف معدات الأندرويد القديمة المطلوبة بالكامل #
          rm -rf android ios
          # من إصدار V2 إنشاء هيكل أندرويد حديث #
          flutter create --org com.staar.playandwin --project-name play_and_win --platforms=android
          flutter pub get
          # تشغيل أداة توليد الأيقونات الجديدة #
          flutter pub run flutter_launcher_icons:main
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
